- name: Configuration commune de toutes les machines
  hosts: all
  become: true

  tasks:

    - name: Installer Les outils de base
      apt:
        name: 
          - curl
          - wget
          - nano
          - net-tools

        state: present